# Generated by Django 5.2.12 on 2026-03-27 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "business_name",
                    models.CharField(default="MyPOS Business", max_length=200),
                ),
                ("business_address", models.TextField(blank=True, default="")),
                (
                    "business_phone",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "business_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "business_logo",
                    models.ImageField(blank=True, null=True, upload_to="logo/"),
                ),
                ("currency", models.CharField(default="GHS", max_length=10)),
                ("currency_symbol", models.CharField(default="₵", max_length=5)),
                (
                    "tax_rate",
                    models.DecimalField(decimal_places=2, default=15.0, max_digits=5),
                ),
                ("tax_name", models.CharField(default="VAT", max_length=50)),
                (
                    "receipt_footer",
                    models.TextField(
                        blank=True, default="Thank you for your business!"
                    ),
                ),
                ("low_stock_threshold", models.IntegerField(default=10)),
                (
                    "mtn_momo_number",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "vodafone_cash_number",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "airteltigo_number",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("enable_barcode_scanner", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "App Settings",
                "verbose_name_plural": "App Settings",
            },
        ),
    ]
